modLoader="javafml" #mandatory
loaderVersion="[31,)"
license="MIT"

[[mods]]
modId="flowstone"
version="forge-1.15.2-1.1.0.1"
displayName="Flowstone"
authors="Niv_Oridocs" #optional
description='''
When lava and water meet
'''

[[dependencies.flowstone]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"